Repository thoth-station/mi, pull requests merged in 2019-12, with the labels that each got.

#4 Correct typo in CODEOWNERS
  .github/CODEOWNERS
Labels: approved, size/XS

#3 refactor code and correct the update knowledge functionality
  .zuul.yaml
  create_bot_knowledge.py
  pr_reviewer.py
  template/__init__.py
  template/version.py
Labels: approved, bug, enhancement, size/XXL

#5 Feature/expand data collection from prs
  create_bot_knowledge.py
Labels: approved, enhancement, size/L
