Repository thoth-station/mi, pull requests merged in 2020-11, with the labels that each got.

#268 Add Forks as features
  srcopsmetrics/entities/fork.py
Labels: approved, size/M

#269 Automatic update of dependency numpy from 1.19.3 to 1.19.4
  Pipfile.lock
Labels: approved, bot, size/L

#270 Automatic update of dependency pandas from 1.1.3 to 1.1.4
  Pipfile.lock
Labels: approved, bot, size/L

#272 Automatic update of dependency thoth-storages from 0.25.15 to 0.25.16
  Pipfile.lock
Labels: approved, bot, size/L

#275 Store additions and deletions for every week
  srcopsmetrics/entities/code_frequency.py
Labels: approved, enhancement, size/M

#276 Add Commits as entities
  srcopsmetrics/entities/commit.py
  srcopsmetrics/entities/pull_request.py
Labels: approved, size/M

#279 Automatic update of dependency thoth-storages from 0.25.16 to 0.26.0
  Pipfile.lock
Labels: approved, bot, size/M

#277 Fix local and remote knowledge store and load
  srcopsmetrics/bot_knowledge.py
  srcopsmetrics/entities/interface.py
  srcopsmetrics/enums.py
  srcopsmetrics/github_knowledge.py
  srcopsmetrics/iterator.py
Labels: approved, enhancement, size/S

#281 Remove unnecesary multiple initializations
  srcopsmetrics/iterator.py
Labels: approved, bug, size/XS

#280 Fix/kebechet update entity
  srcopsmetrics/entities/kebechet_update_manager.py
Labels: approved, bug, size/M

#282 Add christoph as approver
  OWNERS
Labels: approved, size/XS

#283 Automatic update of dependency thoth-storages from 0.26.0 to 0.26.1
  Pipfile.lock
Labels: approved, bot, size/M

#285 Release of version 2.1.0
  CHANGELOG.md
  srcopsmetrics/__init__.py
Labels: approved, bot, size/M

#290 Fix/dependency update author
  srcopsmetrics/entities/commit.py
  srcopsmetrics/entities/dependency_update.py
Labels: approved, size/S

#286 Add specific labels to issues
  srcopsmetrics/entities/issue.py
  srcopsmetrics/entities/pull_request.py
  srcopsmetrics/entities/tools/knowledge.py
Labels: approved, size/M
