Repository thoth-station/mi, pull requests merged in 2020-05, with the labels that each got.

#101 Automatic update of dependency pygithub from 1.50 to 1.51
  Pipfile.lock
Labels: bot, size/M

#102 Automatic update of dependency numpy from 1.18.3 to 1.18.4
  Pipfile.lock
Labels: bot, size/M

#94 Feature/preprocess storage
  srcopsmetrics/bot_knowledge.py
  srcopsmetrics/cli.py
  srcopsmetrics/enums.py
  srcopsmetrics/evaluate_scores.py
  srcopsmetrics/processing.py
  srcopsmetrics/storage.py
  srcopsmetrics/utils.py
  srcopsmetrics/visualization.py
Labels: approved, size/XL

#104 Automatic update of dependency rope from 0.16.0 to 0.17.0
  Pipfile.lock
Labels: bot, size/M

#105 Automatic update of dependency plotly from 4.6.0 to 4.7.0
  Pipfile.lock
Labels: bot, size/S

#106 Automatic update of dependency pytest from 5.4.1 to 5.4.2
  Pipfile.lock
Labels: bot, size/M

#107 Automatic update of dependency plotly from 4.7.0 to 4.7.1
  Pipfile.lock
Labels: bot, size/XS

#108 Automatic update of dependency thoth-storages from 0.22.9 to 0.22.10
  Pipfile.lock
Labels: bot, size/M

#103 Feature/statistics storage
  Pipfile
  Pipfile.lock
  srcopsmetrics/bot_knowledge.py
  srcopsmetrics/cli.py
  srcopsmetrics/github_knowledge.py
  srcopsmetrics/processing.py
  srcopsmetrics/report.py
  srcopsmetrics/storage.py
  srcopsmetrics/visualization.py
Labels: approved, size/XL

#111 Automatic update of dependency dash from 1.11.0 to 1.12.0
  Pipfile.lock
Labels: bot, size/L

#112 Release of version 2.0.0
  CHANGELOG.md
  srcopsmetrics/__init__.py
Labels: approved, bot, size/L

#114 Automatic update of dependency numpy from 1.18.4 to 1.19.0rc1
  Pipfile.lock
Labels: bot, size/L

#116 Automatic update of dependency thoth-storages from 0.22.10 to 0.22.11
  Pipfile.lock
Labels: bot, size/L

#117 Automatic update of dependency pytest-cov from 2.8.1 to 2.9.0
  Pipfile.lock
Labels: bot, size/S

#118 Automatic update of dependency plotly from 4.7.1 to 4.8.0
  Pipfile.lock
Labels: bot, size/S

#119 Automatic update of dependency plotly from 4.8.0 to 4.8.1
  Pipfile.lock
Labels: bot, size/M

#120 Automatic update of dependency pandas from 1.0.3 to 1.0.4
  Pipfile.lock
Labels: bot, size/M

#122 Automatic update of dependency thoth-storages from 0.22.11 to 0.22.12
  Pipfile.lock
Labels: bot, size/XS

#123 Automatic update of dependency autopep8 from 1.5.2 to 1.5.3
  Pipfile.lock
Labels: bot, size/M
