Repository thoth-station/mi, pull requests merged in 2020-03, with the labels that each got.

#59 Feature/cronjob
  openshift/buildConfig-template.yaml
  openshift/configMap-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
  openshift/secret-template.yaml
  srcopsmetrics/cli.py
Labels: approved, size/L

#60 Feature/repos projects organizations
  srcopsmetrics/cli.py
  srcopsmetrics/github_knowledge.py
Labels: approved, size/M

#62 Automatic update of dependency matplotlib from 3.2.0rc3 to 3.2.0
  Pipfile.lock
Labels: bot, size/L

#64 Release of version 1.0.1
  CHANGELOG.md
  srcopsmetrics/__init__.py
Labels: bot, size/S

#65 Release of version 1.0.2
  CHANGELOG.md
  srcopsmetrics/__init__.py
Labels: bot, size/L

#63 Automatic update of dependency plotly from 4.5.2 to 4.5.3
  Pipfile.lock
Labels: bot, size/XS

#66 Automatic update of dependency plotly from 4.5.3 to 4.5.4
  Pipfile.lock
Labels: bot, size/S

#67 Automatic update of dependency pytest from 5.3.5 to 5.4.0
  Pipfile.lock
Labels: bot, size/XS

#68 Automatic update of dependency pytest from 5.4.0 to 5.4.1
  Pipfile.lock
Labels: bot

#69 Automatic update of dependency pygithub from 1.46 to 1.47
  Pipfile.lock
Labels: bot, size/M

#70 Automatic update of dependency pandas from 1.0.1 to 1.0.2
  Pipfile.lock
Labels: bot, size/M

#72 Automatic update of dependency numpy from 1.18.1 to 1.18.2
  Pipfile.lock
Labels: bot, size/L

#73 Automatic update of dependency matplotlib from 3.2.0 to 3.2.1
  Pipfile.lock
Labels: bot, size/M

#74 Automatic update of dependency pandas from 1.0.2 to 1.0.3
  Pipfile.lock
Labels: bot, size/M

#75 Automatic update of dependency thoth-storages from 0.22.3 to 0.22.5
  Pipfile.lock
Labels: bot, size/XS

#76 fix secrets and config name + fix cli call
  openshift/cronJob-template.yaml
Labels: approved, size/S

#77 Automatic update of dependency thoth-storages from 0.22.5 to 0.22.6
  Pipfile.lock
Labels: bot, size/M

#78 Make logger pretty again, fix unknown bug
  srcopsmetrics/bot_knowledge.py
  srcopsmetrics/github_knowledge.py
  srcopsmetrics/github_knowledge_store.py
Labels: approved, size/S

#79 Automatic update of dependency thoth-storages from 0.22.6 to 0.22.7
  Pipfile.lock
Labels: bot, size/M

#80 store issue ids as str in dict
  srcopsmetrics/github_knowledge.py
Labels: approved
