Repository thoth-station/mi, pull requests merged in 2020-02, with the labels that each got.

#43 Automatic update of dependency matplotlib from 3.2.0rc1 to 3.2.0rc3
  Pipfile.lock
Labels: bot, size/M

#44 Automatic update of dependency pandas from 1.0.0 to 1.0.1
  Pipfile.lock
Labels: bot, size/M

#45 Automatic update of dependency thoth-storages from 0.21.11 to 0.22.0
  Pipfile.lock
Labels: bot, size/L

#46 Automatic update of dependency pygithub from 1.45 to 1.46
  Pipfile.lock
Labels: bot, size/S

#47 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#49 Release of version 0.2.3
  CHANGELOG.md
  srcopsmetrics/__init__.py
Labels: bot, size/S

#50 Automatic update of dependency thoth-storages from 0.22.0 to 0.22.1
  Pipfile.lock
Labels: bot, size/M

#51 Automatic update of dependency thoth-storages from 0.22.1 to 0.22.2
  Pipfile.lock
Labels: bot, size/S

#38 Add TTCI plots for visualization
  Pipfile
  Pipfile.lock
  srcopsmetrics/create_bot_knowledge.py
  srcopsmetrics/evaluate_scores.py
  srcopsmetrics/pre_processing.py
  srcopsmetrics/utils.py
  srcopsmetrics/visualization.py
Labels: approved, size/XL

#53 Automatic update of dependency plotly from 4.5.0 to 4.5.1
  Pipfile.lock
Labels: bot, size/L

#52 Fix/ceph
  srcopsmetrics/cli.py
  srcopsmetrics/create_bot_knowledge.py
  srcopsmetrics/evaluate_scores.py
  srcopsmetrics/pre_processing.py
  srcopsmetrics/utils.py
  srcopsmetrics/visualization.py
Labels: approved, size/L

#55 Automatic update of dependency plotly from 4.5.1 to 4.5.2
  Pipfile.lock
Labels: bot, size/M

#56 Automatic update of dependency thoth-storages from 0.22.2 to 0.22.3
  Pipfile.lock
Labels: bot, size/M

#54 Divide classes by context
  srcopsmetrics/bot_knowledge.py
  srcopsmetrics/cli.py
  srcopsmetrics/create_bot_knowledge.py
  srcopsmetrics/entity_schema.py
  srcopsmetrics/enums.py
  srcopsmetrics/evaluate_scores.py
  srcopsmetrics/github_knowledge.py
  srcopsmetrics/github_knowledge_store.py
  srcopsmetrics/pre_processing.py
  srcopsmetrics/utils.py
  srcopsmetrics/visualization.py
Labels: approved, size/XXL

#58 Release of version 1.0.0
  CHANGELOG.md
  srcopsmetrics/__init__.py
Labels: bot, size/M
