Repository thoth-station/mi, pull requests merged in 2020-08, with the labels that each got.

#180 Remove visualizations
  srcopsmetrics/report.py
  srcopsmetrics/visualization.py
Labels: approved, size/XL

#181 Remove coala, fix pipenv update
  Pipfile
  Pipfile.lock
Labels: approved, size/XXL

#182 Automatic update of dependency matplotlib from 3.3.0 to 3.3.1
  Pipfile.lock
Labels: approved, bot

#179 Clear errors issued by pre-commit (visualizations and report excluded)
  README.rst
  openshift/buildConfig-template.yaml
  openshift/configMap-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
  openshift/secret-template.yaml
  openshift/srcopsmetrics-template.yaml
  srcopsmetrics/bot_knowledge.py
  srcopsmetrics/cli.py
  srcopsmetrics/evaluate_scores.py
  srcopsmetrics/github_knowledge.py
  srcopsmetrics/iterator.py
  srcopsmetrics/processing.py
  srcopsmetrics/storage.py
  workflows/templates/workflow-template.yaml
Labels: approved, size/XL

#183 Automatic update of dependency thoth-storages from 0.25.0 to 0.25.1
  Pipfile.lock
Labels: approved, bot

#184 Automatic update of dependency pytest-cov from 2.10.0 to 2.10.1
  Pipfile.lock
Labels: approved, bot, size/M
