Repository thoth-station/mi, pull requests merged in 2020-01, with the labels that each got.

#6 Introduce CLI and refactor code
  .gitignore
  Pipfile
  Pipfile.lock
  README.md
  pr_reviewer.py
  src_ops_metrics/__init__.py
  src_ops_metrics/cli.py
  src_ops_metrics/create_bot_knowledge.py
  src_ops_metrics/evaluate_scores.py
  src_ops_metrics/exceptions.py
  src_ops_metrics/pre_processing.py
  src_ops_metrics/utils.py
  src_ops_metrics/visualization.py
Labels: approved, size/XXL

#15 Automatic update of dependency numpy from 1.18.0 to 1.18.1
  Pipfile.lock
Labels: bot, size/L

#16 Automatic update of dependency pygithub from 1.44.1 to 1.45
  Pipfile.lock
Labels: bot, size/S

#17 Automatic update of dependency pandas from 0.25.3 to 1.0.0rc0
  Pipfile.lock
Labels: bot, size/M

#18 Automatic update of dependency pytest-timeout from 1.3.3 to 1.3.4
  Pipfile.lock
Labels: bot, size/XS

#19 Automatic update of dependency pytest from 5.3.2 to 5.3.3
  Pipfile.lock
Labels: bot, size/XS

#21 Automatic update of dependency pytest from 5.3.3 to 5.3.4
  Pipfile.lock
Labels: bot, size/S

#23 Make a new release job in zuul
  .zuul.yaml
Labels: approved, size/XS

#20 Feature/python package
  .gitignore
  Pipfile
  Pipfile.lock
  setup.py
  src_ops_metrics/__init__.py
  srcopsmetrics/__init__.py
  srcopsmetrics/cli.py
  srcopsmetrics/create_bot_knowledge.py
  srcopsmetrics/evaluate_scores.py
  srcopsmetrics/exceptions.py
  srcopsmetrics/pre_processing.py
  srcopsmetrics/utils.py
  srcopsmetrics/visualization.py
Labels: approved, size/XL

#25 Release of version 0.1.0
  CHANGELOG.md
  srcopsmetrics/__init__.py
Labels: bot, size/M

#26 Fix/imports and pypi
  .gitignore
  Pipfile
  Pipfile.lock
  app.py
  setup.py
  srcopsmetrics/cli.py
  srcopsmetrics/create_bot_knowledge.py
  srcopsmetrics/evaluate_scores.py
  srcopsmetrics/pre_processing.py
  srcopsmetrics/visualization.py
Labels: approved, size/L

#28 Release of version 0.2.0
  CHANGELOG.md
  srcopsmetrics/__init__.py
Labels: bot, size/XS

#29 Fix intendation error from rstcheck
  README.md
Labels: approved, size/XS

#32 Release of version 0.2.1
  CHANGELOG.md
  srcopsmetrics/__init__.py
Labels: bot, size/XS

#31 Refactor src_ops_metrics to srcopsmetrics
  README.md
  srcopsmetrics/evaluate_scores.py
  srcopsmetrics/visualization.py
Labels: approved, size/S

#33 Increase timeout to 50ms
  srcopsmetrics/create_bot_knowledge.py
Labels: approved, size/XS

#35 Release of version 0.2.2
  CHANGELOG.md
  srcopsmetrics/__init__.py
Labels: bot, size/XS

#37 Add API rate limit check and wait
  srcopsmetrics/cli.py
  srcopsmetrics/create_bot_knowledge.py
  srcopsmetrics/utils.py
Labels: size/L

#40 Automatic update of dependency thoth-storages from 0.21.10 to 0.21.11
  Pipfile.lock
Labels: bot, size/M

#41 Automatic update of dependency pytest from 5.3.4 to 5.3.5
  Pipfile.lock
Labels: bot, size/L

#42 Automatic update of dependency pandas from 1.0.0rc0 to 1.0.0
  Pipfile.lock
Labels: bot, size/M
