Repository thoth-station/mi, pull requests merged in 2020-10, with the labels that each got.

#233 Automatic update of dependency pandas from 1.1.2 to 1.1.3
  Pipfile.lock
Labels: approved, bot, size/M

#234 Automatic update of dependency thoth-storages from 0.25.11 to 0.25.15
  Pipfile.lock
Labels: approved, bot, size/M

#236 Automatic update of dependency plotly from 4.10.0 to 4.11.0
  Pipfile.lock
Labels: approved, bot, size/M

#238 Automatic update of dependency pytest from 6.0.2 to 6.1.1
  Pipfile.lock
Labels: approved, bot

#240 Automatic update of dependency pytest from 6.0.2 to 6.1.1
  Pipfile.lock
Labels: approved, bot, size/XS

#243 Automatic update of dependency rope from 0.17.0 to 0.18.0
  Pipfile.lock
Labels: approved, bot, size/S

#246 Automatic update of dependency dash from 1.16.2 to 1.16.3
  Pipfile.lock
Labels: approved, bot, size/XS

#254 Update issue templates from template project
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
Labels: approved, size/M

#255 Add Stars as Entity
  srcopsmetrics/entities/stargazer.py
Labels: approved, enhancement, size/M

#252 Rename current contentfile to ReadMe
  srcopsmetrics/entities/__init__.py
  srcopsmetrics/entities/content_file.py
Labels: approved, size/S

#251 Feature/kebechet update manager
  README.rst
  srcopsmetrics/bot_knowledge.py
  srcopsmetrics/entities/dependency_update.py
  srcopsmetrics/entities/interface.py
  srcopsmetrics/entities/kebechet_update.py
  srcopsmetrics/iterator.py
Labels: approved, kind/feature, size/L

#253 Add Release entity
  Pipfile
  Pipfile.lock
  srcopsmetrics/entities/__init__.py
  srcopsmetrics/entities/release.py
  srcopsmetrics/entities/stargazer.py
  srcopsmetrics/processing.py
Labels: approved, enhancement, hacktoberfest-accepted, size/L

#259 Remove plotly and dash, visualizations no longer present
  Pipfile
  Pipfile.lock
Labels: approved, hacktoberfest-accepted, size/XL, thoth/human_intervention_required

#263 Fix/cached knowledge
  srcopsmetrics/entities/dependency_update.py
  srcopsmetrics/entities/interface.py
  srcopsmetrics/entities/issue.py
  srcopsmetrics/entities/kebechet_update.py
  srcopsmetrics/entities/pull_request.py
  srcopsmetrics/entities/readme.py
  srcopsmetrics/entities/release.py
  srcopsmetrics/entities/stargazer.py
  srcopsmetrics/entities/template.py
  srcopsmetrics/iterator.py
Labels: approved, kind/bug, size/L

#264 Automatic update of dependency numpy from 1.19.2 to 1.19.3
  Pipfile.lock
Labels: approved, bot, size/L

#265 Automatic update of dependency pytest from 6.1.1 to 6.1.2
  Pipfile.lock
Labels: approved, bot, size/L

#266 Fix stargazers
  srcopsmetrics/entities/stargazer.py
Labels: approved, size/XS
