Repository thoth-station/mi, pull requests merged in 2020-07, with the labels that each got.

#164 pre-commit config added
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  README.rst
  pyproject.toml
  setup.py
  srcopsmetrics/bot_knowledge.py
  srcopsmetrics/cli.py
  srcopsmetrics/entity_schema.py
  srcopsmetrics/evaluate_scores.py
  srcopsmetrics/github_knowledge.py
  srcopsmetrics/iterator.py
  srcopsmetrics/processing.py
  srcopsmetrics/report.py
  srcopsmetrics/storage.py
  srcopsmetrics/utils.py
  srcopsmetrics/visualization.py
Labels: approved, size/XL

#171 Release of version 2.0.1
  CHANGELOG.md
  srcopsmetrics/__init__.py
Labels: approved, bot, size/M

#174 Add diagram & note
  README.rst
Labels: approved, size/M

#168 Feature/storage path env var
  setup.py
  srcopsmetrics/bot_knowledge.py
  srcopsmetrics/cli.py
  srcopsmetrics/enums.py
  srcopsmetrics/evaluate_scores.py
  srcopsmetrics/github_knowledge.py
  srcopsmetrics/iterator.py
  srcopsmetrics/processing.py
  srcopsmetrics/report.py
  srcopsmetrics/storage.py
  srcopsmetrics/utils.py
  srcopsmetrics/visualization.py
Labels: approved, size/L
