Repository thoth-station/mi, pull requests merged in 2020-06, with the labels that each got.

#125 Automatic update of dependency numpy from 1.19.0rc1 to 1.19.0rc2
  Pipfile.lock
Labels: bot, size/M

#113 Fix/readme
  README.rst
  setup.py
Labels: approved, size/M

#126 Automatic update of dependency pytest from 5.4.2 to 5.4.3
  Pipfile.lock
Labels: bot, size/S

#139 Automatic update of dependency numpy from 1.19.0rc2 to 1.18.5
  Pipfile.lock
Labels: bot, size/L

#140 Automatic update of dependency pytest-cov from 2.9.0 to 2.10.0
  Pipfile.lock
Labels: bot, size/XS

#141 Automatic update of dependency coala-bears from 0.12.0.dev20171110210444 to 0.11.1
  Pipfile.lock
Labels: bot, size/XS

#144 Relock
  .gitignore
  Pipfile.lock
Labels: approved, size/L

#146 Automatic update of dependency numpy from 1.19.0rc2 to 1.18.5
  Pipfile.lock
Labels: bot, size/L

#147 Automatic update of dependency coala-bears from 0.12.0.dev20171110210444 to 0.11.1
  Pipfile.lock
Labels: bot, size/XS

#148 Do not use pre-preleases
  Pipfile
  Pipfile.lock
Labels: approved, size/XL

#151 Fix processing on Ceph
  srcopsmetrics/storage.py
  srcopsmetrics/visualization.py
Labels: approved, size/XS

#154 Automatic update of dependency thoth-storages from 0.23.0 to 0.23.2
  Pipfile.lock
Labels: bot, size/L

#153 Automatic update of dependency pandas from 1.0.4 to 1.0.5
  Pipfile.lock
Labels: bot, size/M

#156 Automatic update of dependency dash from 1.13.1 to 1.13.2
  Pipfile.lock
Labels: bot, size/XS

#160 Automatic update of dependency dash from 1.13.2 to 1.13.3
  Pipfile.lock
Labels: approved, bot

#162 Automatic update of dependency numpy from 1.18.5 to 1.19.0
  Pipfile.lock
Labels: approved, bot
