Repository thoth-station/mi, pull requests merged in 2020-04, with the labels that each got.

#81 Automatic update of dependency plotly from 4.5.4 to 4.6.0
  Pipfile.lock
Labels: bot, size/M

#82 Follow standards
  README.md
  openshift/configMap-template.yaml
  openshift/cronJob-template.yaml
  openshift/secret-template.yaml
  srcopsmetrics/cli.py
  srcopsmetrics/evaluate_scores.py
  srcopsmetrics/github_knowledge.py
  srcopsmetrics/github_knowledge_store.py
Labels: approved, size/L

#85 Automatic update of dependency autopep8 from 1.5 to 1.5.1
  Pipfile.lock
Labels: bot, size/L

#87 Fix/safe knowledge storing
  Pipfile.lock
  srcopsmetrics/entity_schema.py
  srcopsmetrics/evaluate_scores.py
  srcopsmetrics/github_knowledge.py
  srcopsmetrics/iterator.py
  srcopsmetrics/pre_processing.py
  srcopsmetrics/storage.py
  srcopsmetrics/visualization.py
Labels: approved, size/XL

#86 Fix/issues links are not identified
  srcopsmetrics/github_knowledge.py
Labels: approved, size/M

#88 Add content file to collect readme files
  README.md
  srcopsmetrics/bot_knowledge.py
  srcopsmetrics/entity_schema.py
  srcopsmetrics/enums.py
  srcopsmetrics/github_knowledge.py
  srcopsmetrics/iterator.py
  srcopsmetrics/storage.py
Labels: approved, size/L

#90 Add tutorial on how to add new entity
  README.md
Labels: approved, size/S

#89 Fix/visualization atpi
  srcopsmetrics/pre_processing.py
  srcopsmetrics/visualization.py
Labels: approved, size/L

#92 Automatic update of dependency numpy from 1.18.2 to 1.18.3
  Pipfile.lock
Labels: bot, size/M

#93 Automatic update of dependency autopep8 from 1.5.1 to 1.5.2
  Pipfile.lock
Labels: bot, size/XS

#97 Automatic update of dependency pygithub from 1.47 to 1.50
  Pipfile.lock
Labels: bot, size/M

#99 Automatic update of dependency thoth-storages from 0.22.7 to 0.22.8
  Pipfile.lock
Labels: bot, size/XS

#100 Automatic update of dependency thoth-storages from 0.22.8 to 0.22.9
  Pipfile.lock
Labels: bot, size/M
