Repository thoth-station/mi, pull requests merged in 2021-04, with the labels that each got.

#361 Support multiple repositories
  srcopsmetrics/cli.py
Labels: approved, size/M

#362 Remove codeowners file
  .github/CODEOWNERS
Labels: approved, size/XS

#364 Add statistics aggregation for daily data
  srcopsmetrics/cli.py
  srcopsmetrics/entities/tools/storage.py
  srcopsmetrics/kebechet_metrics.py
Labels: approved, size/L

#370 Link README with MI Indicators
  Pipfile
  Pipfile.lock
  README.rst
Labels: approved, size/L

#376 Save data even though it can be inconsistent
  srcopsmetrics/entities/interface.py
  srcopsmetrics/iterator.py
Labels: approved, size/S

#375 Add 60 seconds to waiting time, use tqdm for logger
  Pipfile
  Pipfile.lock
  srcopsmetrics/cli.py
  srcopsmetrics/iterator.py
Labels: approved, size/L

#363 Feature - Use pandas dataframes
  srcopsmetrics/entities/interface.py
  srcopsmetrics/entities/issue.py
  srcopsmetrics/entities/pull_request.py
  srcopsmetrics/entities/tools/storage.py
Labels: approved, size/M

#377 Change PR structure
  srcopsmetrics/entities/pull_request.py
  srcopsmetrics/iterator.py
Labels: approved, size/M
