Repository thoth-station/mi, pull requests merged in 2022-02, with the labels that each got.

#514 Add token specification to readme
  README.rst
Labels: approved, size/S

#517 Fix entity loading
  srcopsmetrics/bot_knowledge.py
Labels: approved, size/XS

#521 Update templates from template-project
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/deliver_missing_module.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/kebechet_update.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/L

#525 Fix section heading
  README.rst
Labels: approved, size/XS

#524 Update pre-commit configuration
  .pre-commit-config.yaml
  .prow.yaml
Labels: approved, size/M

#541 Change the ordering of parameters
  srcopsmetrics/entities/interface.py
Labels: approved, size/XS

#545 Fix module loading example typo
  srcopsmetrics/entities/README.rst
Labels: approved, size/XS

#546 Add Raw entities for Issue,PullRequest
  srcopsmetrics/entities/raw_issue.py
  srcopsmetrics/entities/raw_pull_request.py
Labels: approved, size/L

#547 Make issue extraction initialization shorter
  srcopsmetrics/entities/issue.py
Labels: approved, size/XS
